apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-uivd
spec:
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: guestbook-uivd
  template:
    metadata:
      labels:
        app: guestbook-uivd
    spec:
      containers:
      - name: guestbook-uivd
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
